// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DoorItem: typeof import('./src/components/door-item/index.vue')['default']
    NavBar: typeof import('./src/components/NavBar/index.vue')['default']
    ReviewCard: typeof import('./src/components/review-card/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceIcon: typeof import('./src/components/service-icon/index.vue')['default']
    SmartIcon: typeof import('./src/components/smart-icon/index.vue')['default']
    SmartInput: typeof import('./src/components/smart-input/index.vue')['default']
    SmartItem: typeof import('./src/components/smart-item/index.vue')['default']
    SmartListItem: typeof import('./src/components/smart-list-item/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    Tabbar: typeof import('./src/components/Tabbar/index.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanRadio: typeof import('vant/es')['Radio']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
  }
}
