// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DoorItem: typeof import('./src/components/door-item/index.vue')['default']
    NavBar: typeof import('./src/components/NavBar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmartIcon: typeof import('./src/components/smart-icon/index.vue')['default']
    SmartInput: typeof import('./src/components/smart-input/index.vue')['default']
    SmartItem: typeof import('./src/components/smart-item/index.vue')['default']
    SmartListItem: typeof import('./src/components/smart-list-item/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    Tabbar: typeof import('./src/components/Tabbar/index.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanDatetimePicker: typeof import('vant/es')['DatetimePicker']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanInput: typeof import('vant/es')['Input']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanRadio: typeof import('vant/es')['Radio']
    VanSpace: typeof import('vant/es')['Space']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTimePicker: typeof import('vant/es')['TimePicker']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
